version: '3.8'
services:
  app:
    build: ./app
    container_name: app_container
    ports:
      - '8080:8080'
    command: npm run serve
    dns:
     - '8.8.8.8'
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
      VUE_APP_API_ENDPOINT: http://localhost:3000

  api:
    container_name: api_container
    build: ./api
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./api:/api
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: 1
      GOOGLE_APPLICATION_CREDENTIALS: /api/config/vuefirebasefb-firebase-adminsdk.json
      TZ: Asia/Tokyo
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./db/cnf/character-set.cnf:/etc/mysql/conf.d/character-set.cnf
      - db-store:/var/lib/mysql

volumes:
  db-store: