version: '3.8'
services:
  app:
    build: ./docker/app
    container_name: app_container
    ports:
      - '8080:8080'
    dns:
     - '8.8.8.8'
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo

  api:
    container_name: api_container
    build: ./docker/api
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: 1
      TZ: Asia/Tokyo
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./dicker/db/cnf/character-set.cnf:/etc/mysql/conf.d/character-set.cnf
      - db-store:/var/lib/mysql

volumes:
  db-store: